language: java
jdk:
  - openjdk8
  - openjdk11
sudo: true
dist: xenial
install: /bin/true
notifications:
  email:
    - github-awsforjava@amazon.com
script: mvn -q install

after_success:
    - bash <(curl -s https://codecov.io/bash) -F unittests

branches:
  only:
    - master
